#!/bin/bash

APP_NAME=nscmr

function usage()
{
    echo
    echo "Script to get an interactive shell with full access to app"
    echo "Usage:"
    echo "      get_interactive [mode | help]"
    echo "mode -> specify the app's running mode (dev, test or prod)"
    echo "help -> prints this text"
    echo
}

if [[ "$1" ]]; then
    case "$1" in
        dev)
            MODE=development
            ;;
        test)
            MODE=testing
            ;;
        prod)
            MODE=production
            ;;
        *)
            echo
            echo "Wrong usage"
            usage
            exit 1
            ;;
    esac
    FLASK_APP_MODE="$MODE" ipython -i "$APP_NAME"/__init__.py
else
    usage
    exit 0
fi

