#!/bin/bash
###############################################################################
###############################################################################
#                                                                             #
#   build_template                                                            #
#                                                                             #
###############################################################################
#                                                                             #
#   Basic script for creating jinja templates.                                #
#                                                                             #
#   It requires at least one argument, which is the name of the template to   #
#   be generated. If a second argument is supplied, this will be the template #
#   which the new template will inherit from. If none is supplied, the new    #
#   template will inherit from 'base.html'.                                   #
#                                                                             #
#   NOTE: do not include the html extension to neither of the arguments.      #
#                                                                             #
#                                                                             #
###############################################################################
#   author: tls                                                               #
#   date: 2016-03-03                                                          #
###############################################################################
###############################################################################

function usage {
    echo
    echo "Wrong usage."
    echo
    echo "Usage:"
    echo "          ${0} template_name [extended_template]"
    echo
    echo "if no extended_template is provided, the new template will extend"
    echo "from base.html"
}

function main {
    TEMP_HEADER="{% extends '${2}.html' %}"
    case "$2" in
        usersidebar)
            read -d '' TEMP_BODY << EOF
{% block main_content %}

{% endblock %}
EOF
            TEMPLATE="${TEMP_HEADER}\n\n${TEMP_BODY}"
            ;;
        *)
            TEMPLATE="${TEMP_HEADER}"
            ;;
    esac
    echo -e "${TEMPLATE}" >> "${1}.html"
}

if [[ ! "$1" ]]; then
    usage
else
    if [[ ! "$2" ]]; then
        main $1 "base"
    else
        main $1 $2
    fi
fi
